POST http://localhost:3000/spwo_db
Content-Type: application/json

{
    "nama_item": "Kertas A4",
    "kategori": "Bahan Pokok",
    "jumlah": 5,
    "harga": 10000,
    "keterangan": "Untuk printer"
}
